static void usage(FILE *stream) {
    fprintf(stream, C_CYAN  "Usage:\n");
    fprintf(stream, C_RESET "    gm <command> <flags>\n");
    fprintf(stream,         "\n");
    fprintf(stream, C_CYAN  "Commands:\n");
    fprintf(stream, C_CYAN  "    <string>\n");
    fprintf(stream, C_RESET "            shortcut to spawn\n");
    fprintf(stream,         "\n");
    fprintf(stream, C_BLUE  "    spawn <repo>\n");
    fprintf(stream,         "            create and/or clone repo from a list of\n");
    fprintf(stream,         "            predefined remotes\n");
    fprintf(stream,         "\n");
    fprintf(stream, C_BLUE  "    modify <repo> <option> <value>\n");
    fprintf(stream, C_RESET "            set remote options\n");
    fprintf(stream,         "\n");
    fprintf(stream, C_BLUE  "    config <option> <value>\n");
    fprintf(stream, C_RESET "            set gimme options\n");
    fprintf(stream,         "\n");
    fprintf(stream, C_BLUE  "    graph <type>\n");
    fprintf(stream, C_RESET "            graph parts of git data\n");
    fprintf(stream,         "\n");
    fprintf(stream, C_BLUE  "    alias <cmd> <alias>\n");
    fprintf(stream, C_RESET "            create gm aliases\n");
    fprintf(stream,         "\n");
    fprintf(stream, C_BLUE  "    breathe <port>\n" );
    fprintf(stream, C_RESET "            git porcelain  that can be ran as a\n");
    fprintf(stream,         "            server for many exteranl applications\n");
    fprintf(stream,         "\n");
    fprintf(stream, C_CYAN  "Flags:\n");
    fprintf(stream, C_BLUE  "    -h --help\n");
    fprintf(stream, C_RESET "            show this message, supply after a\n");
    fprintf(stream,         "            <command> for more command info\n");
}
